import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Monsieur_La_Doulaise,
  Poppins,
  Prosto_One,
} from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const prostoOne = Prosto_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-prosto",
});

const monsieurLaDoulaise = Monsieur_La_Doulaise({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-monsieur-la-doulaise",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gulshan Spa App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  ${prostoOne.variable} ${monsieurLaDoulaise.variable}  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
